services:
  my-nuxt-app:
    build:
      context: .
    container_name: my-nuxt-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - missing-pets_my-shared-network

networks:
  missing-pets_my-shared-network:
    external: true
